### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by TanyaH-create** [TanyaH-create/prework-study-guide#3]
# JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by AbdulAhad365** [comment]
you can use this website https://www.w3schools.com/js/DEFAULT.asp i learn every new topics from here, moreover they have arranged matrial and quizes as well for free

**Comment by tausiiff** [comment]
When did you pass out ?
